env:
  es2021: true
  browser: true

extends:
  - eslint:recommended

plugins:
  - "@stylistic"
  - "import"

parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"

rules:
  semi: ["error", "never"]
  
  "@stylistic/arrow-parens":
    - "error"
    - "as-needed"
    - requireForBlockBody: false

  "@stylistic/brace-style":
    - "error"
    - "1tbs"
    - allowSingleLine: false

  "global-require": "off"
  "import/no-dynamic-require": "off"
  "import/no-extraneous-dependencies": ["error", {"devDependencies": true}]
  "no-underscore-dangle": ["error", {"allow": ["__dirname"]}]
  "import/extensions": "off"
  "import/no-unresolved": "off"
  "no-param-reassign": "off"
  "no-console": "off"
  "no-undef": ["error", {"typeof": true}]
  