---

plugins:
  - jest
  - jest-dom

env:
  jest: true
  browser: true
  es2020: true
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:jest-dom/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  semi: [2, 'never']
  'arrow-parens': [2, 'as-needed']
  'brace-style': [2, '1tbs', { allowSingleLine: true }]
  'import/extensions': 0
  'import/no-unresolved': 0
  'no-param-reassign': 0
  'no-console': 0
  'global-require': 0
  'import/no-dynamic-require': 0
