---
plugins:
  - jest
  - jest-dom

env:
  jest: true
  browser: true
  es2020: true
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:jest-dom/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module

globals:
  __dirname: readonly
  require: readonly
  module: readonly
  process: readonly

rules:
  semi: [2, 'never']
  'arrow-parens': [2, 'as-needed']
  'brace-style': [2, '1tbs', { allowSingleLine: true }]
  'global-require': 0
  'import/no-dynamic-require': 0
  'import/no-extraneous-dependencies': [2, { devDependencies: true }]
  'no-underscore-dangle': [2, { allow: ['__dirname'] }]
  'import/extensions': 0
  'import/no-unresolved': 0
  'no-param-reassign': 0
  'no-console': 0
  'no-undef': [2, { typeof: true }]
  